0.0.0.0/hosts
127.0.0.1/hosts

Remove nordvpn com

---

0.0.0.0/hosts
127.0.0.1/hosts

Hello. Please see [discussion](https://github.com/StevenBlack/hosts/issues/404).

consider including snuff sites

---

0.0.0.0/hosts
127.0.0.1/hosts
Mobile_0_0_0_0/hosts
SafeSearch/hosts

Closes https://github.com/Clefspeare13/pornhosts/issues/94
See also: https://github.com/Import-External-Sources/pornhosts/issues/634

Removed outdated `037jav.com`

---

0.0.0.0/hosts
127.0.0.1/hosts
Mobile_0_0_0_0/hosts
SafeSearch/hosts

Closes https://github.com/Clefspeare13/pornhosts/issues/97
See also:
- https://www.mypdns.org/T656
- https://gitlab.com/my-privacy-dns/matrix/matrix/-/issues/9
- https://github.com/Import-External-Sources/pornhosts/issues/637

Removal `100200film.com`

---

0.0.0.0/hosts
127.0.0.1/hosts
Mobile_0_0_0_0/hosts
SafeSearch/hosts
submit_here/hosts.txt

```python
xvideosnovinhas.com
```
It's a WP site, so only one domain is needed here
</details>
<details><summary>Logger output</summary>
| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +91 | ##.thumb-ads |  | xvideosnovinhas.com |  | dom | `http://xvideosnovinhas.com/` |
| +91 |  |  | xvideosnovinhas.com | 1 | image | `https://xvideosnovinhas.com/wp-content/uploads/2017/03/xvideos.png` |
| +91 |  |  | xvideosnovinhas.com | 1 | script | `http://xvideosnovinhas.com/wp-includes/js/wp-embed.min.js` |
| +91 | \|\|loboclick.com^$3p | -- | xvideosnovinhas.com | 3 | image | `https://loboclick.com/preroll/uploads/15895547255ebeae258756d.png` |
| +91 | …

`xvideosnovinhas.com`

---

0.0.0.0/hosts
127.0.0.1/hosts
Mobile_0_0_0_0/hosts
SafeSearch/hosts

teddygirls.cc

---

0.0.0.0/hosts
127.0.0.1/hosts
Mobile_0_0_0_0/hosts
SafeSearch/hosts

I believe this specific domain(s) is to be moved from the hosts file as it no longer is active for Adult material
```
perfectlexy.blogspot.ro
desiredmia.blogspot.ro
```
```
adoredcassie.blogspot.ro
adorablevickylive.blogspot.ro
beautifulaudrey.blogspot.ro
enjoyableemma.blogspot.ro
ellagraysonlive.blogspot.ro
onechicjoy.blogspot.ro
petitemelissa.blogspot.ro
refinedlover.blogspot.ro
rosemaryevanscam.blogspot.ro
```
<details><Summary>Screenshot</summary>
</details>
- <https://github.com/Import-External-Sources/pornhosts/issues/639>

Removal of two dead blogspot.ro

---

0.0.0.0/hosts
127.0.0.1/hosts
Mobile_0_0_0_0/hosts
SafeSearch/hosts

From https://www.mypdns.org/T709 and https://github.com/spirillen/pornhosts/issues/646

Adding new porno domain `hornygirlhere.com`

---

0.0.0.0/hosts
127.0.0.1/hosts
Mobile_0_0_0_0/hosts
SafeSearch/hosts

`sharesome.com` is an adult social media website

Add sharesome.com

---

0.0.0.0/hosts
127.0.0.1/hosts
Mobile_0_0_0_0/hosts
SafeSearch/hosts

`kantotin.com` is another adult website.
<details>
<summary>Screenshot for verification -- <b>**NSFW**</b></summary>
</details>
_screenshot will be removed from main post once approved, because, well, nsfw_

Add kantotin.com

---

0.0.0.0/hosts
127.0.0.1/hosts
Mobile_0_0_0_0/hosts
SafeSearch/hosts

I spotted a new porn domain that isn't blocked anywhere.

Submit ukrafoto.com

---

submit_here/strict_adult.txt

```python
spb.erobodio.ru
www.erobodio.ru
erobodio.ru
```
from https://github.com/Import-External-Sources/pornhosts/pull/727
</details>

erobodio.ru

---

submit_here/strict_adult.txt

```python
polonews.tw
```
polo-news.disqus.com
</details>

polonews.tw

---

submit_here/hosts.txt

```python
www.cumbuffet.com
cdn.cumbuffet.com
```
</details>

cumbuffet.com

---

submit_here/hosts.txt

```python
m-hentai.net
o.m-hentai.net
```
</details>

m-hentai.net

---

.github/PULL_REQUEST_TEMPLATE.md
submit_here/hosts.txt

```python
www.18plusstream.net
```
</details>

18plusstream.net

---

submit_here/strict_adult.txt

```python
55chan.org
```
very similar to 4chan
https://github.com/Clefspeare13/pornhosts/pull/174#issue-465178404
</details>

55chan.org

---

submit_here/hosts.txt

```python
milenamariaryabushkina.com
```
site hosting lots of porn about this girl
</details>

milenamariaryabushkina.com

---

submit_here/hosts.txt

```python
lewdpatcher.com
```
site about download patches and mods for games or porn games
</details>

lewdpatcher.com

---

submit_here/hosts.txt

```python
sukebei.nyaa.si
```
https://i2.wp.com/sukebei.nyaa.si/
</details>

sukebei.nyaa.si

---

submit_here/hosts.txt

```python
www.redflava.com/
```
https://i0.wp.com/www.redflava.com
https://i1.wp.com/www.redflava.com
https://i2.wp.com/www.redflava.com
</details>

www.redflava.com

---

submit_here/strict_adult.txt

```python
www.4chan.org
```
to complement https://github.com/Clefspeare13/pornhosts/pull/174
</details>

more of 4chan

---

submit_here/hosts.txt

```python
nakedgirlshot.com
```
</details>

nakedgirlshot.com

---

submit_here/hosts.txt

```python
pornotor.org
```
</details>

pornotor.org

---

submit_here/hosts.txt

```python
hotmodelsusa.net
```
propably a bait site for scamming
</details>

hotmodelsusa.net

---

submit_here/hosts.txt

```python
www.mobile-porn.club
```
</details>

mobile-porn

---

submit_here/hosts.txt

```python
masseurporn.com
```
</details>

masseurporn.com

---

submit_here/hosts.txt

```python
www.europornstar.com
```
</details>

europornstar.com

---

submit_here/hosts.txt

```python
www.thenude.com
static.thenude.com
```
</details>

thenude.com

---

submit_here/hosts.txt

```python
analvids.com
```
</details>

analvids.com

---

submit_here/hosts.txt

```python
trailers1.bangbros.com
bangbros.com
images2.bangbros.com
x-images1.bangbros.com
x-images2.bangbros.com
x-images3.bangbros.com
x-images4.bangbros.com
x-images5.bangbros.com
```
not sure if this is all
</details>

bangbros.com

---

submit_here/hosts.txt

```python
viralporn.com
assets-cdn.viralporn.com
cdn.viralporn.com
```
</details>

viralporn.com

---

submit_here/hosts.txt

```python
avforme.com
media.avforme.com
```
</details>

avforme.com

---

submit_here/hosts.txt

```python
www.idoldouganew.com
```
</details>

idoldouganew.com

---

submit_here/hosts.txt

```python
www.jkseifukufetish.com
```
</details>

jkseifukufetish.com

---

submit_here/hosts.txt

```python
www.tokyokinky.com
```
</details>

tokyokinky.com

---

submit_here/hosts.txt

```python
www.focusarmy.com
```
</details>

focusarmy.com

---

submit_here/hosts.txt

```python
nanairo.co
```
</details>

nanairo.co

---

submit_here/hosts.txt

```python
erojapanese.com
```
</details>

erojapanese.com

---

submit_here/hosts.txt

```python
ejaver.com
```
</details>

ejaver.com

---

submit_here/hosts.txt

```python
hentai4free.net
```
</details>

hentai4free.net

---

submit_here/hosts.txt

```python
jerkdolls.com
```
probably a bait site
</details>

jerkdolls.com

---

submit_here/hosts.txt

```python
www.pornnetworkdeals.com
static.pornnetworkdeals.com
```
</details>

pornnetworkdeals.com

---

submit_here/hosts.txt

```python
www.curvyerotic.com
```
</details>

curvyerotic.com

---

submit_here/hosts.txt

```python
nhentai.net
t.nhentai.net
static.nhentai.net
i.nhentai.net
```
</details>

nhentai.net

---

submit_here/hosts.txt

```python
pornedup.com
```
</details>

pornedup.com

---

submit_here/hosts.txt

```python
hentai2read.com
```
all i could find, maybe there's more to be found
</details>

hentai2read.com

---

submit_here/hosts.txt

```python
hentaicdn.com
```
part of https://github.com/Clefspeare13/pornhosts/pull/205
</details>

hentaicdn.com

---

submit_here/hosts.txt

```python
www.akiba-web.com
```
Akiba-web 
</details>

akiba-web.com

---

submit_here/hosts.txt

```python
styles.lemmecheck.net
```
part of https://github.com/Clefspeare13/pornhosts/pull/212
</details>

styles.lemmecheck.net

---

submit_here/hosts.txt

```python
www.lemmecheck.com
cdn2.lemmecheck.com
```
</details>

lemmecheck.com

---

submit_here/hosts.txt

```python
www.legalporno.com
account.legalporno.com
```
</details>

legalporno.com

---

submit_here/hosts.txt

```python
www.porn-star.com
```
</details>

www.porn-star.com

---

submit_here/hosts.txt

```python
www.glam0ur.com
content1.glam0ur.com
content2.glam0ur.com
content3.glam0ur.com
content4.glam0ur.com
content5.glam0ur.com
content6.glam0ur.com
contenta.glam0ur.com
```
</details>

glam0ur.com

---

submit_here/hosts.txt

```python
www.100bucksbabes.com
content1.100bucksbabes.com
content2.100bucksbabes.com
content3.100bucksbabes.com
content4.100bucksbabes.com
content5.100bucksbabes.com
content6.100bucksbabes.com
contenta.100bucksbabes.com
```
</details>

100bucksbabes.com

---

submit_here/hosts.txt

```python
www.eroticbeauties.net
content.eroticbeauties.net
static.eroticbeauties.net
```
</details>

eroticbeauties.net

---

submit_here/hosts.txt

```python
www.hqbabes.com
```
</details>

hqbabes.com

---

submit_here/hosts.txt

```python
www.yourdoll.com
```
</details>

yourdoll.com

---

submit_here/hosts.txt

```python
myporn.club
```
its a simple site to download porn via torrent
how the site looks like
example of content in the site
found here https://myporn.club/torrent/e74w0dbd
</details>

myporn.club

---

submit_here/hosts.txt

```python
www.teamskeetdiscount.co
static.teamskeetdiscount.co
```
</details>

teamskeetdiscount.co

---

submit_here/hosts.txt

```python
wetpussygames.com
```
</details>

wetpussygames.com

---

submit_here/hosts.txt

```python
www.5kporn.com
cdn.5kporn.com
secure.cdn.5kporn.com
www2.5kporn.com
```
</details>

5kporn.com

---

submit_here/strict_adult.txt

Closes <https://github.com/Clefspeare13/pornhosts/issues/256>
Comes from the submission of <https://www.mypdns.org/T1282>

imagetwist.com

---

submit_here/hosts.txt

```python
avsox.cyou
```
</details>

avsox.cyou

---

submit_here/hosts.txt

```python
www.badgirlsblog.com
images.badgirlsblog.com
```
</details>

badgirlsblog.com

---

submit_here/hosts.txt

```python
www.blacked.com
assets-js.blacked.com
```
</details>

blacked.com

---

submit_here/hosts.txt

```python
www.boobieblog.com
```
</details>

boobieblog.com

---

submit_here/hosts.txt

```python
www.brazzers.com
```
</details>

www.brazzers.com

---

submit_here/hosts.txt

```python
www.bustybloom.com
contenta.bustybloom.com
content0.bustybloom.com
content2.bustybloom.com
content3.bustybloom.com
content4.bustybloom.com
content5.bustybloom.com
content6.bustybloom.com
```
</details>

bustybloom.com

---

submit_here/hosts.txt

```python
cherrypimps.com
cdn.cherrypimps.com
```
</details>

cherrypimps.com

---

submit_here/hosts.txt

```python
cuckoldcom.com
```
</details>

cuckoldcom.com

---

submit_here/hosts.txt

```python
daftsex.com
```
</details>

daftsex.com

---

submit_here/hosts.txt

```python
sexhd.pics
```
</details>

sexhd.pics

---

submit_here/hosts.txt

```python
yuajav.com
```
</details>

yuajav.com

---

submit_here/hosts.txt

```python
javhaven.com
```
</details>

javhaven.com

---

submit_here/hosts.txt

```python
javbitcoin.com
```
</details>

javbitcoin.com

---

submit_here/hosts.txt

```python
uralesbian.com
cdn.uralesbian.com
```
</details>

uralesbian.com

---

submit_here/hosts.txt

```python
www.legsjapan.com
cdn.legsjapan.com
```
</details>

legsjapan.com/

---

submit_here/hosts.txt

```python
shadbase.us
```
extra for https://github.com/Import-External-Sources/pornhosts/pull/724
</details>

shadbase.us

---

submit_here/hosts.txt

```python
hookuphotshot.com
join.hookuphotshot.com
```
</details>

hookuphotshot.com

---

submit_here/snuff.txt

Closes https://github.com/Clefspeare13/pornhosts/issues/140

Removal elblogdelnarco.com

---

submit_here/hosts.txt
submit_here/mobile.txt

Closes https://github.com/Clefspeare13/pornhosts/issues/142

Removal: vrshemaletube.com
